# conda env create -f environment.yml
name: clisops-docs
channels:
- conda-forge
- defaults
dependencies:
- sphinx
- nbsphinx
- ipython
- pandoc
- pip
- numpy>=1.16
- xarray>=0.15
- pandas>=1.0.3
- cftime>=1.4.1
- netCDF4>=1.4
- xesmf>=0.5.2
- poppler>=0.67
- shapely>=1.6
- geopandas>=0.7
- dask>=2.6.0
- pyproj>=2.5
- roocs-utils>=0.2.1
- cf_xarray>=0.3.1
